/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as ServicesZohoRouteImport } from './routes/services/zoho'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services/software-development'
import { Route as ServicesSapRouteImport } from './routes/services/sap'
import { Route as ServicesSalesforceRouteImport } from './routes/services/salesforce'
import { Route as ServicesItInfrastructureRouteImport } from './routes/services/it-infrastructure'
import { Route as ServicesCyberSecurityRouteImport } from './routes/services/cyber-security'
import { Route as ServicesCxoAdvisoryRouteImport } from './routes/services/cxo-advisory'
import { Route as ServicesAnalyticsRouteImport } from './routes/services/analytics'
import { Route as ProductsTyreHealthRouteImport } from './routes/products/tyre-health'
import { Route as ProductsSurakshaRouteImport } from './routes/products/suraksha'
import { Route as ProductsSupplierPortalRouteImport } from './routes/products/supplier-portal'
import { Route as ProductsQmsRouteImport } from './routes/products/qms'
import { Route as ProductsPjpRouteImport } from './routes/products/pjp'
import { Route as ProductsCwmsRouteImport } from './routes/products/cwms'
import { Route as IndustriesUtilitiesRouteImport } from './routes/industries/utilities'
import { Route as IndustriesTransportationServicesLogisticsRouteImport } from './routes/industries/transportation-services-logistics'
import { Route as IndustriesMiningRouteImport } from './routes/industries/mining'
import { Route as IndustriesEngineeringConstructionOperationsRouteImport } from './routes/industries/engineering-construction-operations'
import { Route as IndustriesDiscreteManufacturingRouteImport } from './routes/industries/discrete-manufacturing'
import { Route as IndustriesCapitalGoodsRouteImport } from './routes/industries/capital-goods'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ServicesDetailSlugRouteImport } from './routes/services/detail.$slug'
import { Route as ServicesCategoryServiceRouteImport } from './routes/services/$category.$service'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesZohoRoute = ServicesZohoRouteImport.update({
  id: '/services/zoho',
  path: '/services/zoho',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/services/software-development',
    path: '/services/software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSapRoute = ServicesSapRouteImport.update({
  id: '/services/sap',
  path: '/services/sap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSalesforceRoute = ServicesSalesforceRouteImport.update({
  id: '/services/salesforce',
  path: '/services/salesforce',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesItInfrastructureRoute =
  ServicesItInfrastructureRouteImport.update({
    id: '/services/it-infrastructure',
    path: '/services/it-infrastructure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCyberSecurityRoute = ServicesCyberSecurityRouteImport.update({
  id: '/services/cyber-security',
  path: '/services/cyber-security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCxoAdvisoryRoute = ServicesCxoAdvisoryRouteImport.update({
  id: '/services/cxo-advisory',
  path: '/services/cxo-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAnalyticsRoute = ServicesAnalyticsRouteImport.update({
  id: '/services/analytics',
  path: '/services/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTyreHealthRoute = ProductsTyreHealthRouteImport.update({
  id: '/products/tyre-health',
  path: '/products/tyre-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSurakshaRoute = ProductsSurakshaRouteImport.update({
  id: '/products/suraksha',
  path: '/products/suraksha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSupplierPortalRoute = ProductsSupplierPortalRouteImport.update({
  id: '/products/supplier-portal',
  path: '/products/supplier-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsQmsRoute = ProductsQmsRouteImport.update({
  id: '/products/qms',
  path: '/products/qms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPjpRoute = ProductsPjpRouteImport.update({
  id: '/products/pjp',
  path: '/products/pjp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCwmsRoute = ProductsCwmsRouteImport.update({
  id: '/products/cwms',
  path: '/products/cwms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesUtilitiesRoute = IndustriesUtilitiesRouteImport.update({
  id: '/industries/utilities',
  path: '/industries/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesTransportationServicesLogisticsRoute =
  IndustriesTransportationServicesLogisticsRouteImport.update({
    id: '/industries/transportation-services-logistics',
    path: '/industries/transportation-services-logistics',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesMiningRoute = IndustriesMiningRouteImport.update({
  id: '/industries/mining',
  path: '/industries/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesEngineeringConstructionOperationsRoute =
  IndustriesEngineeringConstructionOperationsRouteImport.update({
    id: '/industries/engineering-construction-operations',
    path: '/industries/engineering-construction-operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDiscreteManufacturingRoute =
  IndustriesDiscreteManufacturingRouteImport.update({
    id: '/industries/discrete-manufacturing',
    path: '/industries/discrete-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesCapitalGoodsRoute = IndustriesCapitalGoodsRouteImport.update({
  id: '/industries/capital-goods',
  path: '/industries/capital-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDetailSlugRoute = ServicesDetailSlugRouteImport.update({
  id: '/services/detail/$slug',
  path: '/services/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryServiceRoute = ServicesCategoryServiceRouteImport.update({
  id: '/services/$category/$service',
  path: '/services/$category/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/capital-goods': typeof IndustriesCapitalGoodsRoute
  '/industries/discrete-manufacturing': typeof IndustriesDiscreteManufacturingRoute
  '/industries/engineering-construction-operations': typeof IndustriesEngineeringConstructionOperationsRoute
  '/industries/mining': typeof IndustriesMiningRoute
  '/industries/transportation-services-logistics': typeof IndustriesTransportationServicesLogisticsRoute
  '/industries/utilities': typeof IndustriesUtilitiesRoute
  '/products/cwms': typeof ProductsCwmsRoute
  '/products/pjp': typeof ProductsPjpRoute
  '/products/qms': typeof ProductsQmsRoute
  '/products/supplier-portal': typeof ProductsSupplierPortalRoute
  '/products/suraksha': typeof ProductsSurakshaRoute
  '/products/tyre-health': typeof ProductsTyreHealthRoute
  '/services/analytics': typeof ServicesAnalyticsRoute
  '/services/cxo-advisory': typeof ServicesCxoAdvisoryRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/it-infrastructure': typeof ServicesItInfrastructureRoute
  '/services/salesforce': typeof ServicesSalesforceRoute
  '/services/sap': typeof ServicesSapRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/zoho': typeof ServicesZohoRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/services/detail/$slug': typeof ServicesDetailSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/capital-goods': typeof IndustriesCapitalGoodsRoute
  '/industries/discrete-manufacturing': typeof IndustriesDiscreteManufacturingRoute
  '/industries/engineering-construction-operations': typeof IndustriesEngineeringConstructionOperationsRoute
  '/industries/mining': typeof IndustriesMiningRoute
  '/industries/transportation-services-logistics': typeof IndustriesTransportationServicesLogisticsRoute
  '/industries/utilities': typeof IndustriesUtilitiesRoute
  '/products/cwms': typeof ProductsCwmsRoute
  '/products/pjp': typeof ProductsPjpRoute
  '/products/qms': typeof ProductsQmsRoute
  '/products/supplier-portal': typeof ProductsSupplierPortalRoute
  '/products/suraksha': typeof ProductsSurakshaRoute
  '/products/tyre-health': typeof ProductsTyreHealthRoute
  '/services/analytics': typeof ServicesAnalyticsRoute
  '/services/cxo-advisory': typeof ServicesCxoAdvisoryRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/it-infrastructure': typeof ServicesItInfrastructureRoute
  '/services/salesforce': typeof ServicesSalesforceRoute
  '/services/sap': typeof ServicesSapRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/zoho': typeof ServicesZohoRoute
  '/industries': typeof IndustriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/services/detail/$slug': typeof ServicesDetailSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/team': typeof TeamRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/industries/capital-goods': typeof IndustriesCapitalGoodsRoute
  '/industries/discrete-manufacturing': typeof IndustriesDiscreteManufacturingRoute
  '/industries/engineering-construction-operations': typeof IndustriesEngineeringConstructionOperationsRoute
  '/industries/mining': typeof IndustriesMiningRoute
  '/industries/transportation-services-logistics': typeof IndustriesTransportationServicesLogisticsRoute
  '/industries/utilities': typeof IndustriesUtilitiesRoute
  '/products/cwms': typeof ProductsCwmsRoute
  '/products/pjp': typeof ProductsPjpRoute
  '/products/qms': typeof ProductsQmsRoute
  '/products/supplier-portal': typeof ProductsSupplierPortalRoute
  '/products/suraksha': typeof ProductsSurakshaRoute
  '/products/tyre-health': typeof ProductsTyreHealthRoute
  '/services/analytics': typeof ServicesAnalyticsRoute
  '/services/cxo-advisory': typeof ServicesCxoAdvisoryRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/it-infrastructure': typeof ServicesItInfrastructureRoute
  '/services/salesforce': typeof ServicesSalesforceRoute
  '/services/sap': typeof ServicesSapRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/zoho': typeof ServicesZohoRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/services/detail/$slug': typeof ServicesDetailSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/team'
    | '/blog/$slug'
    | '/industries/capital-goods'
    | '/industries/discrete-manufacturing'
    | '/industries/engineering-construction-operations'
    | '/industries/mining'
    | '/industries/transportation-services-logistics'
    | '/industries/utilities'
    | '/products/cwms'
    | '/products/pjp'
    | '/products/qms'
    | '/products/supplier-portal'
    | '/products/suraksha'
    | '/products/tyre-health'
    | '/services/analytics'
    | '/services/cxo-advisory'
    | '/services/cyber-security'
    | '/services/it-infrastructure'
    | '/services/salesforce'
    | '/services/sap'
    | '/services/software-development'
    | '/services/zoho'
    | '/industries/'
    | '/products/'
    | '/services/'
    | '/services/$category/$service'
    | '/services/detail/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/team'
    | '/blog/$slug'
    | '/industries/capital-goods'
    | '/industries/discrete-manufacturing'
    | '/industries/engineering-construction-operations'
    | '/industries/mining'
    | '/industries/transportation-services-logistics'
    | '/industries/utilities'
    | '/products/cwms'
    | '/products/pjp'
    | '/products/qms'
    | '/products/supplier-portal'
    | '/products/suraksha'
    | '/products/tyre-health'
    | '/services/analytics'
    | '/services/cxo-advisory'
    | '/services/cyber-security'
    | '/services/it-infrastructure'
    | '/services/salesforce'
    | '/services/sap'
    | '/services/software-development'
    | '/services/zoho'
    | '/industries'
    | '/products'
    | '/services'
    | '/services/$category/$service'
    | '/services/detail/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/team'
    | '/blog_/$slug'
    | '/industries/capital-goods'
    | '/industries/discrete-manufacturing'
    | '/industries/engineering-construction-operations'
    | '/industries/mining'
    | '/industries/transportation-services-logistics'
    | '/industries/utilities'
    | '/products/cwms'
    | '/products/pjp'
    | '/products/qms'
    | '/products/supplier-portal'
    | '/products/suraksha'
    | '/products/tyre-health'
    | '/services/analytics'
    | '/services/cxo-advisory'
    | '/services/cyber-security'
    | '/services/it-infrastructure'
    | '/services/salesforce'
    | '/services/sap'
    | '/services/software-development'
    | '/services/zoho'
    | '/industries/'
    | '/products/'
    | '/services/'
    | '/services/$category/$service'
    | '/services/detail/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  TeamRoute: typeof TeamRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesCapitalGoodsRoute: typeof IndustriesCapitalGoodsRoute
  IndustriesDiscreteManufacturingRoute: typeof IndustriesDiscreteManufacturingRoute
  IndustriesEngineeringConstructionOperationsRoute: typeof IndustriesEngineeringConstructionOperationsRoute
  IndustriesMiningRoute: typeof IndustriesMiningRoute
  IndustriesTransportationServicesLogisticsRoute: typeof IndustriesTransportationServicesLogisticsRoute
  IndustriesUtilitiesRoute: typeof IndustriesUtilitiesRoute
  ProductsCwmsRoute: typeof ProductsCwmsRoute
  ProductsPjpRoute: typeof ProductsPjpRoute
  ProductsQmsRoute: typeof ProductsQmsRoute
  ProductsSupplierPortalRoute: typeof ProductsSupplierPortalRoute
  ProductsSurakshaRoute: typeof ProductsSurakshaRoute
  ProductsTyreHealthRoute: typeof ProductsTyreHealthRoute
  ServicesAnalyticsRoute: typeof ServicesAnalyticsRoute
  ServicesCxoAdvisoryRoute: typeof ServicesCxoAdvisoryRoute
  ServicesCyberSecurityRoute: typeof ServicesCyberSecurityRoute
  ServicesItInfrastructureRoute: typeof ServicesItInfrastructureRoute
  ServicesSalesforceRoute: typeof ServicesSalesforceRoute
  ServicesSapRoute: typeof ServicesSapRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesZohoRoute: typeof ServicesZohoRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesCategoryServiceRoute: typeof ServicesCategoryServiceRoute
  ServicesDetailSlugRoute: typeof ServicesDetailSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/zoho': {
      id: '/services/zoho'
      path: '/services/zoho'
      fullPath: '/services/zoho'
      preLoaderRoute: typeof ServicesZohoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/services/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sap': {
      id: '/services/sap'
      path: '/services/sap'
      fullPath: '/services/sap'
      preLoaderRoute: typeof ServicesSapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/salesforce': {
      id: '/services/salesforce'
      path: '/services/salesforce'
      fullPath: '/services/salesforce'
      preLoaderRoute: typeof ServicesSalesforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/it-infrastructure': {
      id: '/services/it-infrastructure'
      path: '/services/it-infrastructure'
      fullPath: '/services/it-infrastructure'
      preLoaderRoute: typeof ServicesItInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cyber-security': {
      id: '/services/cyber-security'
      path: '/services/cyber-security'
      fullPath: '/services/cyber-security'
      preLoaderRoute: typeof ServicesCyberSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cxo-advisory': {
      id: '/services/cxo-advisory'
      path: '/services/cxo-advisory'
      fullPath: '/services/cxo-advisory'
      preLoaderRoute: typeof ServicesCxoAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/analytics': {
      id: '/services/analytics'
      path: '/services/analytics'
      fullPath: '/services/analytics'
      preLoaderRoute: typeof ServicesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/tyre-health': {
      id: '/products/tyre-health'
      path: '/products/tyre-health'
      fullPath: '/products/tyre-health'
      preLoaderRoute: typeof ProductsTyreHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/suraksha': {
      id: '/products/suraksha'
      path: '/products/suraksha'
      fullPath: '/products/suraksha'
      preLoaderRoute: typeof ProductsSurakshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/supplier-portal': {
      id: '/products/supplier-portal'
      path: '/products/supplier-portal'
      fullPath: '/products/supplier-portal'
      preLoaderRoute: typeof ProductsSupplierPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/qms': {
      id: '/products/qms'
      path: '/products/qms'
      fullPath: '/products/qms'
      preLoaderRoute: typeof ProductsQmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pjp': {
      id: '/products/pjp'
      path: '/products/pjp'
      fullPath: '/products/pjp'
      preLoaderRoute: typeof ProductsPjpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/cwms': {
      id: '/products/cwms'
      path: '/products/cwms'
      fullPath: '/products/cwms'
      preLoaderRoute: typeof ProductsCwmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/utilities': {
      id: '/industries/utilities'
      path: '/industries/utilities'
      fullPath: '/industries/utilities'
      preLoaderRoute: typeof IndustriesUtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/transportation-services-logistics': {
      id: '/industries/transportation-services-logistics'
      path: '/industries/transportation-services-logistics'
      fullPath: '/industries/transportation-services-logistics'
      preLoaderRoute: typeof IndustriesTransportationServicesLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/mining': {
      id: '/industries/mining'
      path: '/industries/mining'
      fullPath: '/industries/mining'
      preLoaderRoute: typeof IndustriesMiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/engineering-construction-operations': {
      id: '/industries/engineering-construction-operations'
      path: '/industries/engineering-construction-operations'
      fullPath: '/industries/engineering-construction-operations'
      preLoaderRoute: typeof IndustriesEngineeringConstructionOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/discrete-manufacturing': {
      id: '/industries/discrete-manufacturing'
      path: '/industries/discrete-manufacturing'
      fullPath: '/industries/discrete-manufacturing'
      preLoaderRoute: typeof IndustriesDiscreteManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/capital-goods': {
      id: '/industries/capital-goods'
      path: '/industries/capital-goods'
      fullPath: '/industries/capital-goods'
      preLoaderRoute: typeof IndustriesCapitalGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/detail/$slug': {
      id: '/services/detail/$slug'
      path: '/services/detail/$slug'
      fullPath: '/services/detail/$slug'
      preLoaderRoute: typeof ServicesDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category/$service': {
      id: '/services/$category/$service'
      path: '/services/$category/$service'
      fullPath: '/services/$category/$service'
      preLoaderRoute: typeof ServicesCategoryServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  TeamRoute: TeamRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesCapitalGoodsRoute: IndustriesCapitalGoodsRoute,
  IndustriesDiscreteManufacturingRoute: IndustriesDiscreteManufacturingRoute,
  IndustriesEngineeringConstructionOperationsRoute:
    IndustriesEngineeringConstructionOperationsRoute,
  IndustriesMiningRoute: IndustriesMiningRoute,
  IndustriesTransportationServicesLogisticsRoute:
    IndustriesTransportationServicesLogisticsRoute,
  IndustriesUtilitiesRoute: IndustriesUtilitiesRoute,
  ProductsCwmsRoute: ProductsCwmsRoute,
  ProductsPjpRoute: ProductsPjpRoute,
  ProductsQmsRoute: ProductsQmsRoute,
  ProductsSupplierPortalRoute: ProductsSupplierPortalRoute,
  ProductsSurakshaRoute: ProductsSurakshaRoute,
  ProductsTyreHealthRoute: ProductsTyreHealthRoute,
  ServicesAnalyticsRoute: ServicesAnalyticsRoute,
  ServicesCxoAdvisoryRoute: ServicesCxoAdvisoryRoute,
  ServicesCyberSecurityRoute: ServicesCyberSecurityRoute,
  ServicesItInfrastructureRoute: ServicesItInfrastructureRoute,
  ServicesSalesforceRoute: ServicesSalesforceRoute,
  ServicesSapRoute: ServicesSapRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesZohoRoute: ServicesZohoRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesCategoryServiceRoute: ServicesCategoryServiceRoute,
  ServicesDetailSlugRoute: ServicesDetailSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
